%% Main.m
% =========================================================================
% NEURONAL DATA ANALYZER - MAIN LAUNCHER
% =========================================================================
% Entry point for the NeuroAnalyzer application (NMD Lab). On first run (or
% when no project dirs are set), prompts for Import/Export directories.
% Layout: grid-based content (sections 1–3 + room for more). Section 1:
% Filtering & Signal Processing (LDF and Ephys). Section 2: Imaging & ROI.
% Section 3: Signal Characterization. Project bar: Import/Export paths.
% =========================================================================

classdef Main < handle
    properties
        UIFig
        HeaderPanel
        ProjectPanel
        ImportLabel
        ExportLabel
        ContentPanel
        % Section 1: Filtering & Signal Processing
        ProcessingPanel    % Card containing LDF and Ephys panels
        LDFPanel
        EphysPanel
        ExtractLDFBtn
        ProcessLDFBtn
        AverageLDFBtn
        ExtractEphysBtn
        LFPAnalysisBtn
        ProcessMUABtn
        % Section 2: Imaging & ROI
        ImagingPanel
        % Section 3: Signal Characterization
        CharPanel
        CharBtn            % Open Signal Characterization
        HelpBtn
        AuthorLabel
    end

    methods
        function app = Main()
            app.buildUI();
            % Prompt for project directories if not set (optional: only when no dirs)
            if ~ProjectManager.hasProject()
                ProjectManager.promptForProjectDirs();
                app.updateProjectLabels();
            end
        end

        function buildUI(app)
            T = UITheme;
            % Larger window: supports 3 sections + room for future (EEG, imaging, etc.)
            figW = 1040;
            figH = 780;
            app.UIFig = uifigure('Name', 'Neuronal Data Analyzer Lab', ...
                'Position', [320 80 figW figH], 'Resize', 'on', 'Color', T.bgGray);

            % === MAIN GRID: Header | Project bar | Content | Footer ===
            mainGrid = uigridlayout(app.UIFig, [4, 1], ...
                'RowHeight', {T.headerHeight, 52, '1x', T.footerHeight}, ...
                'Padding', [0 0 0 0], 'RowSpacing', 0, ...
                'ColumnSpacing', 0, ...
                'BackgroundColor', T.bgGray);

            % === HEADER ===
            app.HeaderPanel = uipanel(mainGrid, ...
                'BackgroundColor', T.headerBg, 'BorderType', 'none');
            headerGrid = uigridlayout(app.HeaderPanel, [1, 2], ...
                'ColumnWidth', {'1x', 90}, 'RowHeight', {'1x'}, ...
                'Padding', [24 14 20 14], 'ColumnSpacing', 8, ...
                'BackgroundColor', T.headerBg);
            uilabel(headerGrid, 'Text', 'Neuronal Data Analyzer Lab', ...
                'FontSize', T.fontTitle, 'FontWeight', 'bold', 'FontColor', T.headerTitleColor, ...
                'VerticalAlignment', 'center');
            app.HelpBtn = uibutton(headerGrid, 'push', ...
                'Text', 'Help', ...
                'BackgroundColor', [1 1 1], 'FontColor', T.headerBg, 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @(~,~)HelpApp());

            % === PROJECT BAR ===
            app.ProjectPanel = uipanel(mainGrid, ...
                'BackgroundColor', T.projectBarBg, ...
                'BorderType', 'line', 'HighlightColor', T.projectBarBorder);
            projGrid = uigridlayout(app.ProjectPanel, [1, 5], ...
                'ColumnWidth', {50, '1x', 50, '1x', 130}, 'RowHeight', {'1x'}, ...
                'Padding', [14 10 14 10], 'ColumnSpacing', 6, ...
                'BackgroundColor', T.projectBarBg);
            uilabel(projGrid, 'Text', 'Import:', ...
                'FontWeight', 'bold', 'FontSize', T.fontSmall, ...
                'VerticalAlignment', 'center');
            app.ImportLabel = uilabel(projGrid, 'Text', '(not set)', ...
                'FontSize', T.fontSmall, ...
                'FontColor', T.bodyColor, 'Interpreter', 'none', ...
                'VerticalAlignment', 'center');
            uilabel(projGrid, 'Text', 'Export:', ...
                'FontWeight', 'bold', 'FontSize', T.fontSmall, ...
                'VerticalAlignment', 'center');
            app.ExportLabel = uilabel(projGrid, 'Text', '(not set)', ...
                'FontSize', T.fontSmall, ...
                'FontColor', T.bodyColor, 'Interpreter', 'none', ...
                'VerticalAlignment', 'center');
            uibutton(projGrid, 'push', ...
                'Text', 'Set Directories', ...
                'ButtonPushedFcn', @(~,~)app.onSetDirectories());

            % === CONTENT: grid of sections ===
            % To add a section: increase rows in contentGrid (e.g. 9,1), add RowHeight
            % entries {24, 260, 24, 88, 24, 80, 24, 60, '1x'}, then add title label + panel.
            app.ContentPanel = uipanel(mainGrid, ...
                'BackgroundColor', T.bgGray, 'BorderType', 'none');
            contentGrid = uigridlayout(app.ContentPanel, [7, 1], ...
                'RowHeight', {24, 260, 24, 88, 24, 80, '1x'}, ...
                'Padding', [16 12 16 12], 'RowSpacing', 8);

            % --- Row 1: Section 1 title ---
            uilabel(contentGrid, 'Text', '1. Filtering & Signal Processing', ...
                'FontSize', T.fontSection, 'FontWeight', 'bold', 'FontColor', T.sectionTitleColor);

            % --- Row 2: Processing (LDF + Ephys) card with 1x2 inner grid ---
            app.ProcessingPanel = uipanel(contentGrid, ...
                'Title', '', 'BackgroundColor', T.cardBg, ...
                'HighlightColor', T.cardBorder, 'BorderType', 'line');
            procGrid = uigridlayout(app.ProcessingPanel, [1, 2], ...
                'ColumnWidth', {'1x', '1x'}, 'Padding', [12 12 12 12], 'ColumnSpacing', 12);

            app.LDFPanel = uipanel(procGrid, ...
                'Title', 'LDF (Laser Doppler Flowmetry)', ...
                'BackgroundColor', T.cardBg, 'HighlightColor', T.cardBorder, ...
                'FontWeight', 'bold', 'FontSize', T.fontBody, 'BorderType', 'line');
            lGrid = uigridlayout(app.LDFPanel, [4, 1], ...
                'RowHeight', {'1x', '1x', '1x', 22}, ...
                'Padding', [14 10 14 10], 'RowSpacing', 8);
            app.ExtractLDFBtn = uibutton(lGrid, 'push', ...
                'Text', 'Extract LDF Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Load and extract LDF; crop and save', ...
                'ButtonPushedFcn', @(~,~)ExtractLDFApp());
            app.ProcessLDFBtn = uibutton(lGrid, 'push', ...
                'Text', 'Process LDF Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Filter and segment LDF by stimulus', ...
                'ButtonPushedFcn', @(~,~)ProcessingLDFApp());
            app.AverageLDFBtn = uibutton(lGrid, 'push', ...
                'Text', 'Average LDF Viewer', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Grand average across trials', ...
                'ButtonPushedFcn', @(~,~)LDFGrandAverageApp());
            uilabel(lGrid, 'Text', 'Load → Crop → Process → Average', ...
                'FontSize', T.fontTiny, 'FontColor', T.mutedColor);

            app.EphysPanel = uipanel(procGrid, ...
                'Title', 'Electrophysiology', ...
                'BackgroundColor', T.cardBg, 'HighlightColor', T.cardBorder, ...
                'FontWeight', 'bold', 'FontSize', T.fontBody, 'BorderType', 'line');
            eGrid = uigridlayout(app.EphysPanel, [4, 1], ...
                'RowHeight', {'1x', '1x', '1x', 22}, ...
                'Padding', [14 10 14 10], 'RowSpacing', 8);
            app.ExtractEphysBtn = uibutton(eGrid, 'push', ...
                'Text', 'Extract Ephys Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Load TDT; extract LFP and MUA', ...
                'ButtonPushedFcn', @(~,~)ExtractEphysApp());
            app.LFPAnalysisBtn = uibutton(eGrid, 'push', ...
                'Text', 'Process LFP Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'ERP and CSD analysis', ...
                'ButtonPushedFcn', @(~,~)LFPAnalysisApp());
            app.ProcessMUABtn = uibutton(eGrid, 'push', ...
                'Text', 'Process MUA Data', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Spike sorting and rate', ...
                'ButtonPushedFcn', @(~,~)MUAAnalysisApp());
            uilabel(eGrid, 'Text', 'TDT → LFP / MUA → ERP, CSD, spikes', ...
                'FontSize', T.fontTiny, 'FontColor', T.mutedColor);

            % --- Row 3: Section 2 title ---
            uilabel(contentGrid, 'Text', '2. Imaging & ROI analysis', ...
                'FontSize', T.fontSection, 'FontWeight', 'bold', 'FontColor', T.sectionTitleColor);

            % --- Row 4: Imaging panel ---
            app.ImagingPanel = uipanel(contentGrid, ...
                'Title', 'Coregistered images: ROI/line, brightness, movement, ΔF/F, speed, kymograph, vessel diameter', ...
                'BackgroundColor', T.cardBg, 'HighlightColor', T.cardBorder, ...
                'FontWeight', 'bold', 'FontSize', T.fontBody, 'BorderType', 'line');
            imgLayout = uigridlayout(app.ImagingPanel, [1, 2], ...
                'ColumnWidth', {'1x', 300}, 'Padding', [16 10 16 10]);
            uilabel(imgLayout, 'Text', ...
                'B&W 256, smooth, normalize. Blood flow, 2P, multiphoton, gCaMP, vessel diameter.', ...
                'FontSize', T.fontSmall, 'FontColor', T.bodyColor, 'WordWrap', 'on');
            uibutton(imgLayout, 'push', ...
                'Text', 'Open ROI / Coregistered Image Analysis', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Load stack, draw ROI or line; brightness, movement, ΔF/F, speed, kymograph, vessel diameter', ...
                'ButtonPushedFcn', @(~,~)ROIAnalysisApp());

            % --- Row 5: Section 3 title ---
            uilabel(contentGrid, 'Text', '3. Signal Characterization', ...
                'FontSize', T.fontSection, 'FontWeight', 'bold', 'FontColor', T.sectionTitleColor);

            % --- Row 6: Characterization panel ---
            app.CharPanel = uipanel(contentGrid, ...
                'Title', 'Extract response features from processed or imported data', ...
                'BackgroundColor', T.cardBg, 'HighlightColor', T.cardBorder, ...
                'FontWeight', 'bold', 'FontSize', T.fontBody, 'BorderType', 'line');
            cGrid = uigridlayout(app.CharPanel, [1, 2], ...
                'ColumnWidth', {'1x', 240}, 'Padding', [16 12 16 12]);
            uilabel(cGrid, 'Text', ...
                'Peak latency, onset delay, FWHM, AUC (positive/negative), rise/decay time, stimulation–response integration.', ...
                'FontSize', T.fontSmall, 'FontColor', T.bodyColor, 'WordWrap', 'on');
            app.CharBtn = uibutton(cGrid, 'push', ...
                'Text', 'Open Signal Characterization', ...
                'FontSize', T.fontButton, 'BackgroundColor', T.accent, 'FontColor', [1 1 1], ...
                'Tooltip', 'Load processed data and extract response features', ...
                'ButtonPushedFcn', @(~,~)SignalCharacterizationApp());

            % --- Row 7: Spacer (1x) for future sections; footer in main grid ---
            % (Empty row absorbs extra space; add new section rows above this by inserting before '1x')

            % === FOOTER (main grid row 4) ===
            footerPanel = uipanel(mainGrid, 'BackgroundColor', T.bgGray, 'BorderType', 'none');
            footerGrid = uigridlayout(footerPanel, [1, 1], ...
                'Padding', [16 4 20 4], 'BackgroundColor', T.bgGray);
            app.AuthorLabel = uihyperlink(footerGrid, ...
                'Text', sprintf('© Copyrights by Alejandro Suarez, Ph.D.  ·  v%s', T.version), ...
                'URL', 'https://github.com/alesuarez92', ...
                'FontSize', T.fontSmall, ...
                'FontColor', T.mutedColor, 'HorizontalAlignment', 'right');

            app.updateProjectLabels();
        end

        function onSetDirectories(app)
            ProjectManager.promptForProjectDirs();
            app.updateProjectLabels();
        end

        function updateProjectLabels(app)
            imp = ProjectManager.getImportDir();
            exp = ProjectManager.getExportDir();
            if isempty(imp), imp = '(not set)'; else imp = pathShorten(imp, 42); end
            if isempty(exp), exp = '(not set)'; else exp = pathShorten(exp, 42); end
            app.ImportLabel.Text = imp;
            app.ExportLabel.Text = exp;
        end
    end
end

function s = pathShorten(p, maxLen)
    if length(p) <= maxLen
        s = p;
        return;
    end
    s = ['...' p(end-maxLen+3:end)];
end
