%% Techniques.m
% =========================================================================
% TECHNIQUES - ONE TABLE OF EVERY ANALYSIS AND LEARNING WINDOW
% =========================================================================
% The launcher (Main), Help (HelpApp.demoWindow / websitePage) and the
% tests read this table, so a new technique is one new row in list().
%
%   F = Techniques.families()   families in launcher order: id, name, color
%   T = Techniques.list()       techniques in launcher order:
%       id, short (short name), family, name, description, io, help (topic
%       of the tile's ?),
%       web (website page, optionally 'page#anchor') and steps, a struct
%       array with label, window (class it opens), help (Help topic of
%       that window), tooltip (which file goes in and out) and action
%       ('' = open the window; 'session' = choose a session file and open
%       it in the window that saved it)
%   L = Techniques.learn()      the Learn area: id, name, description,
%       window, help, web ('' = no website page yet), tooltip, available
%       (false = shown with a disabled "Coming soon" button: Course and
%       Virtual lab are not in this release)
%   c = Techniques.windows()    every window class named in the tables
%   [labels, classes] = Techniques.demoChoices()  windows that have demo
%       data, named like the windows ("Extract LDF", "EEG analysis")
%   n = Techniques.windowName(cls)        that name for one window class
%   c = Techniques.windowForTopic(topic)  window a Help topic's demo opens
%   p = Techniques.pageForTopic(topic)    website page of a Help topic
%
% Families follow the website's Analyses menu, so people find things in
% the same place in the app and online. The Learn items have no website
% page while they are not ready.
% =========================================================================

classdef Techniques
    methods (Static)
        %% families - Groups of tiles in the launcher, in order
        function F = families()
            T = UITheme;
            F = struct('id',    {'blood', 'ephys', 'eeg', 'imaging', 'across'}, ...
                       'name',  {'Blood flow', 'Electrophysiology', 'EEG', 'Imaging', 'Across techniques'}, ...
                       'color', {T.plotColors(2, :), T.plotColors(1, :), T.plotColors(4, :), ...
                                 T.plotColors(3, :), T.headerBg});
        end

        %% list - Every analysis tile of the launcher, in order
        function T = list()
            T = [ ...
                tech('ldf', 'LDF', 'blood', 'Laser Doppler flowmetry (LDF)', ...
                    'Blood-flow recordings: crop, filter, cut trials around each stimulus and average them.', ...
                    'In: LabChart, AcqKnowledge, Spike2, EDF or table  ·  Out: trials .mat, grand average', 'LDF Extract', 'ldf', [ ...
                    stp('Extract', 'ExtractLDFApp', 'LDF Extract', ...
                        ['Input: a recording (LabChart, AcqKnowledge .acq, Spike2 .mat, EDF / BDF or a text ' ...
                         'table); the LDF and stimulus channels are guessed from their names. Select a time range and crop. ' ...
                         'Output: cropped .mat with stim, LDF, t, Fs.']), ...
                    stp('Process', 'ProcessingLDFApp', 'LDF Process', ...
                        ['Input: cropped .mat from step 1 (stim, LDF, t, Fs). Downsample, filter and ' ...
                         'segment trials around stimulus onsets. Output: .mat with segmentedLDF ' ...
                         '(trials x samples), segmentedTime, Fs; saving to an existing file appends trials.']), ...
                    stp('Average', 'LDFGrandAverageApp', 'LDF Average', ...
                        ['Input: one or more segmented .mat files from step 2 (segmentedLDF, segmentedTime; ' ...
                         'time axes must match). Output: grand average (mean ± SD) across all trials, ' ...
                         'optionally relative to the pre-stimulus baseline.'])]), ...
                tech('lsci', 'Laser speckle', 'blood', 'Laser speckle flowmetry (LSCI)', ...
                    'Blood-flow maps from laser speckle images: flow over time, responses, where it changed.', ...
                    'In: speckle or perfusion images (.mat, TIFF, video)  ·  Out: flow .csv / .mat, trials', ...
                    'Laser Speckle', 'ldf#laser-speckle', ...
                    stp('Laser speckle', 'LSCIAnalysisApp', 'Laser Speckle', ...
                        ['Input: raw speckle images from the camera (.mat frames or multi-frame TIFF; frame rate, ' ...
                         'exposure and a stimulus trace optional), speckle contrast images, or the perfusion / ' ...
                         'flux images exported by a commercial imaging system. Speckle ' ...
                         'contrast, flow index (1/K^2 or 1/tau_c), flow per ROI over time, trials around each ' ...
                         'stimulus and a response map. Output: .csv / .mat, and the trials as a .mat that LDF ' ...
                         'Average and Response features open.'])), ...
                tech('lfp', 'LFP', 'ephys', 'Local field potentials (LFP)', ...
                    'ERPs, current source density, spectra and time-frequency, per channel.', ...
                    'In: TDT, Intan, Open Ephys, NWB and 8 more formats  ·  Out: LFP .mat, ERP / CSD', 'LFP Analysis', 'ephys', [ ...
                    stp('Extract', 'ExtractEphysApp', 'Ephys Extract', ephysExtractTip()), ...
                    stp('LFP analysis', 'LFPAnalysisApp', 'LFP Analysis', ...
                        ['Input: LFP .mat from step 1 (lfp_data, t_lfp, lfp_fs, stim_data, t_stim, stim_fs). ' ...
                         'ERP: epochs around stimulus onsets averaged per channel; CSD across channels ' ...
                         '(needs the ERP first). Output: ERP / CSD plots and an exported .mat (t, y = channel ' ...
                         'mean ERP, erp_avg, erp_std, csd) that Response features can read.'])]), ...
                tech('mua', 'MUA', 'ephys', 'Multi-unit activity (MUA)', ...
                    'Detect spikes, sort them into units, firing rates around each stimulus.', ...
                    'In: TDT, Intan, Open Ephys, NWB and 8 more formats  ·  Out: MUA .mat, spike times', 'MUA Analysis', 'ephys', [ ...
                    stp('Extract', 'ExtractEphysApp', 'Ephys Extract', ephysExtractTip()), ...
                    stp('MUA analysis', 'MUAAnalysisApp', 'MUA Analysis', ...
                        ['Input: MUA .mat from step 1 (mua_data, mua_fs, t_mua, mua_channels; stim_data ' ...
                         'optional, needed to segment by stimulus). Spike detection, clustering and ' ...
                         'spike rate. Output: .mat with SpikeResults (spike times, cluster IDs, waveforms), ' ...
                         'SpikeSortParams, clusterQuality, info.'])]), ...
                tech('eeg', 'EEG', 'eeg', 'EEG: ERPs and statistics', ...
                    'Scalp or rodent EEG, raw or cleaned: cleaning, trials, ERPs, measures, statistics.', ...
                    'In: BrainVision, EDF, EGI, XDF, EEGLAB, FieldTrip, .mat  ·  Out: .csv / .mat', 'EEG Analysis', 'eeg', ...
                    stp('EEG analysis', 'EEGAnalysisApp', 'EEG Analysis', ...
                        ['Input: one file per participant: a raw recording (BrainVision Recorder .vhdr, EDF / BDF, ' ...
                         'EGI .mff, XDF, EEG-BIDS) or EEG already cleaned in EEGLAB (.set), FieldTrip (.mat), ' ...
                         'BrainVision Analyzer or MATLAB (a plain .mat array; a short form asks what its variables ' ...
                         'are); trials or a continuous recording with events. Electrode layout (from the files, by ' ...
                         '10-5 name or from a positions file); bad channels, filters, re-reference, ' ...
                         'trials around events and amplitude rejection; ERPs per condition, mean or peak amplitude ' ...
                         'in a time window, statistics between conditions, scalp maps, and the time' char(8211) 'frequency of ' ...
                         'each condition (ERSP, phase locking, band power). Output: one row per participant and ' ...
                         'condition as .csv, or everything as .mat.'])), ...
                tech('roi', 'ROI', 'imaging', 'Imaging over time (ROI)', ...
                    'Stacks over time: motion correction, cells, ΔF/F, vessel diameter.', ...
                    'In: .mat, TIFF or microscope stack  ·  Out: time series .csv / .mat', 'ROI Analysis', 'imaging', ...
                    stp('ROI analysis', 'ROIAnalysisApp', 'ROI Analysis', ...
                        ['Input: .mat with stack or frames (H x W x N or H x W x 3 x N; optional timeVec or t ' ...
                         'and roiMask) or a multi-frame TIFF. Output: brightness, movement, ΔF/F, ' ...
                         'kymograph or vessel diameter as .csv or .mat. Motion correction, cell detection, ' ...
                         'kymograph, vessel diameter.'])), ...
                tech('histology', 'Histology', 'imaging', 'Histology and cultures', ...
                    'Still images: align, count cells and markers, per region and per mm².', ...
                    'In: TIFF, PNG / JPG, .mat  ·  Out: cell counts .csv / .mat', 'Histology', 'imaging#histology', ...
                    stp('Histology / culture', 'HistologyApp', 'Histology', ...
                        ['Input: still images of sections or cultures: TIFF (every page a channel), PNG / JPG or ' ...
                         '.mat (images, H x W x channels x images), one or several (sections, time points, wells). ' ...
                         'Align them, count cells, find marker-positive cells, count per region and per mm2. ' ...
                         'Output: cells and counts as .csv or .mat.'])), ...
                tech('features', 'Response features', 'across', 'Response features', ...
                    'Latency, peak, width and area of each response; group statistics and figures.', ...
                    'In: trials or traces from any analysis  ·  Out: feature table .csv / .mat', ...
                    'Signal Characterization', 'features', ...
                    stp('Signal Characterization', 'SignalCharacterizationApp', 'Signal Characterization', ...
                        ['Input: segmented LDF .mat (segmentedLDF, segmentedTime) from LDF step 2, LFP .mat ' ...
                         '(lfp_data, t_lfp) from Extract Ephys, the ERP export of LFP analysis, or any .mat ' ...
                         'with t and y. Output: one row of features per trial, exported as .csv or .mat. ' ...
                         'Group statistics and publication figures (PDF / SVG).'])), ...
                tech('batch', 'Batch', 'across', 'Batch processing', ...
                    'Run one analysis on a whole folder of files with the same settings.', ...
                    'In: a folder of files  ·  Out: one summary table .csv / .mat + log', 'Batch processing', 'batch', ...
                    stp('Batch processing', 'BatchApp', 'Batch processing', ...
                        ['Input: a folder or list of files for one pipeline: cropped LDF .mat (trials + response ' ...
                         'features), LFP .mat (ERP / CSD per channel), MUA .mat (spike sorting per channel), ' ...
                         'EEG files, one per participant (cleaning, trials, ERPs and a measure per condition), ' ...
                         'image stacks (ROI dF/F, vessel diameter) or any trace file (response features). ' ...
                         'Output: one summary table (.csv and .mat, one row per file / channel / condition / ROI) ' ...
                         'and a log; ' ...
                         'files that fail are listed with their error.'])), ...
                tech('sessions', 'Sessions', 'across', 'Sessions and reports', ...
                    'Reopen a saved analysis in its own window, with its settings and files checked.', ...
                    'Every window saves sessions, PDF reports and methods text', 'Sessions and reports', 'sessions', ...
                    stp(['Open a session' char(8230)], '', 'Sessions and reports', ...
                        ['Choose a session file (' Session.Extension ') saved by any window: it opens in that ' ...
                         'window with its files (checked by MD5), settings and results.'], 'session'))];
        end

        %% learn - The Learn area of the launcher, in order
        function L = learn()
            L = [ ...
                lrn('course', 'Course', ...
                    'Step-by-step lessons in the real windows, with sample data and checks. Coming soon.', ...
                    '', 'Welcome', '', ...
                    'Coming soon: step-by-step lessons in the real windows, with sample data and checks', false), ...
                lrn('lab', 'Virtual lab', ...
                    'Plan, record and analyse a simulated experiment, with feedback on every step. Coming soon.', ...
                    '', 'Welcome', '', ...
                    'Coming soon: plan, record and analyse a simulated experiment, with feedback on every step', false)];
        end

        %% windows - Every window class named in the tables (unique, in order)
        function c = windows()
            c = {};
            T = Techniques.list();
            for i = 1:numel(T)
                c = [c, {T(i).steps.window}]; %#ok<AGROW>
            end
            L = Techniques.learn();
            c = [c, {L.window}];
            c = c(~cellfun(@isempty, c));
            [~, k] = unique(c, 'first');
            c = c(sort(k));
        end

        %% demoChoices - Windows that have demo data: labels and classes
        % One entry per window, named like the window: the step name, followed
        % by the short names of the tiles that use it unless it already says
        % it ("Extract LDF", "Extract LFP / MUA", "LFP analysis", "EEG analysis").
        function [labels, classes] = demoChoices()
            classes = {}; shorts = {}; steps = {}; named = [];
            T = Techniques.list();
            for i = 1:numel(T)
                for k = 1:numel(T(i).steps)
                    s = T(i).steps(k);
                    if isempty(s.window), continue; end
                    j = find(strcmp(classes, s.window), 1);
                    if ~isempty(j)
                        shorts{j}{end+1} = T(i).short; %#ok<AGROW>
                        continue;
                    end
                    classes{end+1} = s.window; %#ok<AGROW>
                    shorts{end+1} = {T(i).short}; %#ok<AGROW>
                    steps{end+1} = s.label; %#ok<AGROW>
                    named(end+1) = numel(T(i).steps) == 1 || ~isempty(strfind(s.label, T(i).short)); %#ok<AGROW,STREMP>
                end
            end
            labels = steps;
            for j = find(~named)
                labels{j} = [steps{j} ' ' strjoin(shorts{j}, ' / ')];
            end
        end

        %% windowName - Name of a window class as the demo list shows it (the class if unknown)
        function name = windowName(cls)
            [labels, classes] = Techniques.demoChoices();
            k = find(strcmp(classes, cls), 1);
            if isempty(k), name = char(cls); else, name = labels{k}; end
        end

        %% windowForTopic - Window a Help topic's "Try it" opens ('' = none)
        function cls = windowForTopic(topic)
            cls = '';
            topic = strtrim(char(topic));
            T = Techniques.list();
            for i = 1:numel(T)
                k = find(strcmpi({T(i).steps.help}, topic) & ~cellfun(@isempty, {T(i).steps.window}), 1);
                if ~isempty(k), cls = T(i).steps(k).window; return; end
            end
            L = Techniques.learn();
            k = find(strcmpi({L.help}, topic) & ~strcmp({L.window}, 'HelpApp') & ...
                ~cellfun(@isempty, {L.window}), 1);
            if ~isempty(k), cls = L(k).window; end
        end

        %% pageForTopic - Website page of a Help topic ('' = not in the tables)
        function page = pageForTopic(topic)
            page = '';
            topic = strtrim(char(topic));
            T = Techniques.list();
            for i = 1:numel(T)
                if strcmpi(T(i).help, topic) || any(strcmpi({T(i).steps.help}, topic))
                    page = T(i).web; return;
                end
            end
            L = Techniques.learn();
            k = find(strcmpi({L.help}, topic) & ~strcmpi({L.help}, 'Welcome'), 1);
            if ~isempty(k), page = L(k).web; end
        end
    end
end

%% ------------------------------------------------------------------------
%  Local helpers (one row of a table)
%% ------------------------------------------------------------------------

function t = tech(id, short, family, name, description, io, help, web, steps)
    t = struct('id', id, 'short', short, 'family', family, 'name', name, 'description', description, ...
        'io', io, 'help', help, 'web', web, 'steps', steps);
end

function s = stp(label, window, help, tooltip, action)
    if nargin < 5, action = ''; end
    s = struct('label', label, 'window', window, 'help', help, 'tooltip', tooltip, 'action', action);
end

function l = lrn(id, name, description, window, help, web, tooltip, available)
    l = struct('id', id, 'name', name, 'description', description, 'window', window, ...
        'help', help, 'web', web, 'tooltip', tooltip, 'available', logical(available));
end

function s = ephysExtractTip()
    s = ['Input: a recording from TDT (tank / block folder; needs the TDT MATLAB SDK, README: Install ' ...
         'the TDT SDK), Intan .rhd / .rhs, Open Ephys, NWB, SpikeGLX, Blackrock, Neuralynx, Plexon, ' ...
         'Multi Channel Systems or Axon ABF. Output: LFP .mat (lfp_data, lfp_channels, ' ...
         'lfp_fs, t_lfp, stim_data, stim_fs, t_stim) and MUA .mat (mua_data, mua_channels, ' ...
         'mua_fs, t_mua, stim_*, filterParams).'];
end
